### ISSUE TITLE
Custom Functions

### ISSUE THREAD

**Issue by Harsh4902** [hanazuki/node-jsonnet#252]
- [ ] How to implement custom jsonnet functions for this library?
- [ ] If there is any way for creating custom jsonnet function than please mention it in documantation.

**Comment by hanazuki** [comment]
I suppose the feature you mention is what is called "native functions" or "native callbacks" in Jsonnet terminology.
node-jsonnet has `nativeCallback` function to define a native callback in the Jsonnet execution environment, whose documentation can be found at <https://node-jsonnet.hanazuki.dev/master/classes/Jsonnet.html#nativeCallback> with a tiny example program.

**Comment by Harsh4902** [comment]
Got it. Thank you for helping
