### ISSUE TITLE
I was going through your source code , how you called asynchronous function synchronously in nodejs . 

### ISSUE THREAD

**Issue by redoC-A2k** [hanazuki/node-jsonnet#305]
For example here - 
![image](https://github.com/hanazuki/node-jsonnet/assets/60838316/600b2f0b-8d97-46bb-ab36-4ebb8df3f1ec)
But how you achieved that feat as I think google jsonnet library will call any function synchronously but you made it call async functions also ?

I basically want to know how you used nodejs addon api and made it possible to call async js functions synchronously ?

**Comment by hanazuki** [comment]
Hi. You spotted the most interesting and essential part of the library. The answer exists in `JsonnetNativeCallback.cpp`.

Jsonnet evaluation is done in two threads working cooperatively. One is the Node.js main thread, which runs the JavaScript event loop and evaluates all the JavaScript codes, and the other is a background thread that runs libjsonnet's native code.

1. When you call a `Jsonnet.evaluate*` function in JavaScript, node-jsonnet spawns a native thread, initializes Jsonnet VM in the background thread, and then returns a Promise for the JSON result. The main thread goes back to processing the other JS tasks.
2. Jsonnet VM starts evaluating the Jsonnet program in background. When it finds a call to `std.native`, libjsonnet calls back node-jsonnet. node-jsonnet then queues the corresponding JS function, which may be async, into the Node.js event loop. The background thread sleeps.
3. The main thread eventually picks up and evaluates the queued task.
4. The background thread wakes up, receives the result of Step 3, and continues evaluating the Jsonnet program.

In this way, JS codes run asynchronously and libjsonnet runs synchronously.
See also: https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md
